deploy

diff --git a/.github/workflows/student_course.yml b/.github/workflows/student_course.yml
--- a/.github/workflows/student_course.yml
+++ b/.github/workflows/student_course.yml
@@ -93,15 +93,9 @@ jobs:
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           port: 22
           script: |
-            # Install nvm if not installed
-            if [ ! -s "$HOME/.nvm/nvm.sh" ]; then
-              echo "Installing nvm..."
-              curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.2/install.sh | bash
-              export NVM_DIR="$HOME/.nvm"
-              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
-            fi
+            #!/bin/bash
 
-            # Verify nvm installation
+            # Check if nvm is installed
             if [ -s "$HOME/.nvm/nvm.sh" ]; then
               source "$HOME/.nvm/nvm.sh"
             elif [ -s "/usr/local/nvm/nvm.sh" ]; then
@@ -113,8 +107,8 @@ jobs:
 
             # Verify yarn installation
             if ! command -v yarn &> /dev/null; then
-              echo "Yarn could not be found. Installing yarn..."
-              npm install -g yarn
+              echo "Yarn could not be found"
+              exit 1
             fi
 
             cd /home/ubuntu/app/build
@@ -134,7 +128,8 @@ jobs:
             # Check if the PM2 process is running
             if pm2 show student_course > /dev/null; then
               echo "Application is running. Restarting..."
-              yarn restart
+              pm2 restart student_course
             else
               echo "Application is not running. Starting..."
-              yarn start:dev
+              pm2 start ./src/server.js --name SCM
+            fi
