deploy

diff --git a/.github/workflows/student_course.yml b/.github/workflows/student_course.yml
--- a/.github/workflows/student_course.yml
+++ b/.github/workflows/student_course.yml
@@ -105,10 +105,22 @@ jobs:
               exit 1
             fi
 
-            # Install yarn if not installed
+            # Install npm and yarn if not installed
+            if ! command -v npm &> /dev/null; then
+              echo "npm could not be found, installing npm..."
+              sudo apt update
+              sudo apt install -y nodejs npm
+            fi
+
             if ! command -v yarn &> /dev/null; then
               echo "Yarn could not be found, installing yarn..."
               npm install -g yarn
+            fi
+
+            # Install pm2 if not installed
+            if ! command -v pm2 &> /dev/null; then
+              echo "pm2 could not be found, installing pm2..."
+              npm install -g pm2
             fi
 
             cd /home/ubuntu/app/build
